services:
  postgres:
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=tasks

    volumes:
      - ./db:/var/lib/postgresql/data